language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: omfHxj+g2O+qj2/7+nApyvA+KcS2hi+jWP8AICs8EzQrreR6Ed8wmVwzx2DD9ndmqDFyyeR2DkbwkAkYQAbMLEKFxfhvG42e8PXZUDg4sucwF73iQ/Xccac8YhZ9pXxxWkT3Oxogk5pb3Xy8MY4bmYypmiiId15m/1sepLG9FhotUAQHxFQLrwxh4gslkAfGHE1WdJOC0+wv4u5zqaDaEqV6gfv6X4y88yT0EmSOnT+8hrupy3ImgO8a96FfHXz7d74ic0u0mQ7H0uSk6y82DTLFIEzsyetyAojots12OYeJZE/7rohcEaumEBF5JvzKngsG4FXmBVnX5Mf20zo96vRGoepKjyUD1tDJO7g14QVpkXhjrCPwwsikfPnTPZjgc24CX0oxUq/G9L0ri8ZvMDMCXo6FmVerx2Sw2uB3SN8zCYlUlWg7/tz/9drkYINF6XHjv5M3WGQtVRHtkueg37IlhltZwFIG7wR+1DUytwkLj8MBomimao6AQAiHv/IkLQXa+ZRe1w5MVaoZsyaCJn9oIGcSzOBE4leirhZvIDJ/qUlmkbdO35y6G2hyVpMCgAmo3dOnhceSb3VOa7vnwJVJCySym/HmIZW7VJzyPW4WzPYjMcfNeB4I7Tn6lSy0U8pyflpLpIr3bSBg93MUWk98SgoiVmt/Yk7+v8i84rs=
  file:
    - "remark-retext.js"
    - "remark-retext.min.js"
  on:
    tags: true
