language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: KvwvkV0vXMuLVhw00Lbc1FE0yHccNEw/MTTLCtt3DjWaQHe0AYiKkpea6a+zpSlFQGMrU1E5RGrefnP/64CEwl9pMNJpLRVLQPvfSASe72rHuu/j7MSe8WbHsh6LvM6Vcro+16y1jb9C4ULpApLa9V2eVMknUViqPLbDLeZltpXUpLAzKhwYz3bMjdxCnGle7HFc1q8oWn8LDxsz+R6HcIn1UX7UFlY7kbpIDJ4if/EpCf5nTK1Uj6rgYUsJThl9JLEcv0zNRqV7OTa5VF58YJgd2QbsLe1dgIR+no1zbWxQyXm168ztH76Ak9lwPgB8KVYs+VtlP6M9cK2ZIO9+MCAApgM3eV3z7QDyZ3XAUSB5M38NebnGPUFVV0IH+O1Zj4JV60tKrngwB2omwBN03BAtTQ+s6h+av/j9qyhUDwMeaYRFOaKyCZZqw98tUJir8SveQpucRhDQxQKt54b/DKJglXcA6gMLctSU2Tc811ReWgX9WUxLX9m1zuk4AZsdFzQ8fyJm2uZbQfKOa+OxOWhyvofsY8yWg9rW0uXKFPYim2YADkTGDEXcI3YkrGdmQS7IaGWyZNtSz5JchLIFOmCBn2ffsGSssHi+fOyUMms7Rm49d78gPQW1kp+YD4y9WzYCx0KQ6Fj1farHuQppw0zFfIcQwxS7S4k5QseRahg=
  file:
    - 'remark-retext.js'
    - 'remark-retext.min.js'
  on:
    tags: true
